### PR TITLE
Feature/message

### PR DESCRIPTION
**Pull request by YoungWoong-Cho**
- Add message feature
    - Polling database for message updates
- Add direct message feature to dating and roommate profile

### CODE REVIEW

**Comment by f4ithlin** [comment]
Is there a reason you made polling time lower?

**Comment by YoungWoong-Cho** [comment]
> Is there a reason you made polling time lower?

That's to make the polling update more frequent

**Comment by f4ithlin** [comment]
I see, looks good !

**Review by yurihueee — COMMENTED** [review]
sick work!

**Pull request merged**
